### ISSUE TITLE
[Bug]  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by conscloud** [bestruirui/BestSub#44]
### 验证步骤

- [x] 我已经阅读了 [config.example.yaml](https://github.com/bestruirui/subs-check/blob/master/doc/config.example.yaml)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [README.md](https://github.com/bestruirui/subs-check/blob/master/README.md) 并未解决问题
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/mihomo-check/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
# 是否打印进度 
print-progress: false

rename:
  # 重命名方法 api 或 regex 或 mix
  method: mix
  # 是否显示旗帜信息
  flag: true

check:
  # 并发
  concurrent: 15
  # 检查间隔,单位分钟
  interval: 360
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 2048
  # 下载测试超时时间(s)
  download-timeout: 90
  # 测速地址
  speed-test-url: https://speedtest.xxx.xxx/__down?bytes=524288000
  # 检查项目（根据需要选择）
  items:
    - openai # ChatGPT Android APP 是否可用
    - youtube # YouTube 是否可用
    - netflix # Netflix 是否可用
    - disney # Disney+ 是否可用
    - speed # 测速

save:
  # 保存方法 webdav 或 http 或 gist 或 r2 或 local
  method: gist
  # 使用http保存方式时需要的端口
  port: 8080
  # webdav
  webdav-url: ""
  webdav-username: ""
  webdav-password: ""
  # github token
  github-token: ""
  # gist id
  github-gist-id: ""
  # github api mirror
  github-api-mirror: ""
  #worker-url
  worker-url: https://your-worker-url.com
  #worker-token
  worker-token: your-worker-token

# mihomo api
mihomo-api-url: ""
# mihomo api secret
mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 3
# 代理设置 支持 http 和 socks 代理
proxy:
  type: "http" # 可选值: http, socks
  address: "http://192.168.3.254:7890" # 代理地址
# 订阅链接
sub-urls:
  - https:
```

### 描述

在日志中发现如下报错信息，但是好你不影响最终结果生成
`2025/03/06 11:04:36.818398 [ants]: worker exits from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 11544 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
	github.com/panjf2000/ants/v2@v2.11.1/worker.go:62 +0xe5
panic({0xf08d60?, 0x19dcea0?})
	runtime/panic.go:787 +0x132
net/http.(*Client).do(0x0, 0xc000a96000)
	net/http/client.go:603 +0x1dc
net/http.(*Client).Do(...)
	net/http/client.go:587
github.com/bestruirui/bestsub/proxy/info.(*Proxy).CountryCodeFromApi(0xc000bf4bd0)
	github.com/bestruirui/bestsub/proxy/info/country.go:48 +0xbdb
main.proxyRenameTask(0xc000bf4bd0)
	github.com/bestruirui/bestsub/main.go:298 +0xc5
main.maintask.func2()
	github.com/bestruirui/bestsub/main.go:241 +0x47
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
	github.com/panjf2000/ants/v2@v2.11.1/worker.go:73 +0x8a
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 1
	github.com/panjf2000/ants/v2@v2.11.1/worker.go:50 +0x65`

![Image](https://github.com/user-attachments/assets/6520a097-85b2-4809-a17e-78635339cb59)

### 重现方式

容器环境下
每次执行都会有报错

### 日志

```shell

```
