### ISSUE TITLE
[Bug] 存储在本地的结果，api不触发更新

### ISSUE THREAD

**Issue by molezz** [bestruirui/BestSub#45]
### 验证步骤

- [x] 我已经阅读了 [config.example.yaml](https://github.com/bestruirui/subs-check/blob/master/doc/config.example.yaml)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [README.md](https://github.com/bestruirui/subs-check/blob/master/README.md) 并未解决问题
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/mihomo-check/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
save:
  # Save method: webdav, http, gist, or r2
  method: local
# Mihomo API
mihomo-api-url: "http://127.0.0.1:9090"
# Mihomo API secret
mihomo-api-secret: ""


mihomo config

  sub1:
    type: http
    url: "https://aaa.com"
    interval: 600
    path: ./sub1.yaml
    health-check:
      enable: true
      url: http://www.google.com/generate_204
      interval: 60

  all:
    type: file
    path: D:/downloads/BestSub_Windows_x86_64/output/all.yaml
    health-check:
      enable: true
      interval: 3600
      url: https://cp.cloudflare.com/generate_204
```

### 描述

all.yaml存在本地， 
终端显示update 远程的一些sub成功，但是本地的all没有update， 要手动在面板更新
```
[34mINFO [0m [2025-03-06T14:44:23] update sub sub1 success
[34mINFO [0m [2025-03-06T14:44:25] subs updated
[34mINFO [0m [2025-03-06T14:44:25] next check time: 2025-03-06 15:34:25
```

另外如何看细节log ， 我感觉挺多节点不测速是都在， 但是一测速就没了， 哪怕把速度写成`  min-speed: 1024`
实际运行中， 可以从本地网卡看到， 都有10M的节点， 在all没保留。

### 重现方式

配置local方式
mihomo里用file而不是http

### 日志

```shell
�[34mINFO �[0m [2025-03-06T14:44:23] update sub sub1 success
�[34mINFO �[0m [2025-03-06T14:44:25] subs updated
�[34mINFO �[0m [2025-03-06T14:44:25] next check time: 2025-03-06 15:34:25
```

```
