### ISSUE TITLE
[Feature] 节点去重增加password或者uuid的判断

### ISSUE THREAD

**Issue by TonyJiangWJ** [bestruirui/BestSub#47]
### 验证步骤

- [x] 我已经阅读了 [README.md](https://github.com/bestruirui/subs-check/blob/master/README.md)，确认了该功能没有实现
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/subs-check/issues) 中寻找过我要提出的功能请求，并且没有找到

### 描述

- 感谢佬提供这么好用的工具，我使用过程中遇到这个问题，希望优化一下去重的判断：
- 互联网代理池中，相同服务域名和端口的代理，其password或者uuid（针对vmess和vless是uuid）可能是不同的，而且都有效且独立存在。
- 目前代码中去重是直接按服务地址+端口作为去重的key的，所以会导致一个服务域名和端口配对只能存在一个代理。而此时可能存在多个password，而第一个可能失效了，导致剩下有效的password被丢弃。
- 例如如下两个节点的server和port是相同的，但是password不同，而且都能正常使用：
```yaml
    - cipher: chacha20-ietf-poly1305
      name: TW 004
      password: 538de2b2-xxxxxxxxxxxxxxxxxxx
      port: 47564
      server: gy.666666222.shop
      type: ss
      udp: true
    - cipher: chacha20-ietf-poly1305
      name: TW 130
      password: e7991bb9-xxxxxxxxxxxxxxxxxxx
      port: 47564
      server: gy.666666222.shop
      type: ss
      udp: true
```
