### ISSUE TITLE
[Bug] 测速环节直接跳过

### ISSUE THREAD

**Issue by skybbk1001** [bestruirui/BestSub#50]
### 验证步骤

- [x] 我已经阅读了 [config.example.yaml](https://github.com/bestruirui/subs-check/blob/master/doc/config.example.yaml)，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我仔细看过 [README.md](https://github.com/bestruirui/subs-check/blob/master/README.md) 并未解决问题
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/mihomo-check/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
# 是否打印进度 
print-progress: false

log-level: info

# 重命名方法 api 或 regex 或 mix
rename:
  method: regex
  flag: true

check:
  # Concurrency
  concurrent: 100
  # Check interval, in minutes
  interval: 30
  # Timeout, in milliseconds
  timeout: 2000
  # Minimum speed, in KB/s
  min-speed: 500
  # Download test timeout, in seconds
  download-timeout: 10
  # Speed test URL
  speed-test-url: http://cachefly.cachefly.net/100mb.test
  speed-check-concurrent: 1
  # Items to check
  items:
    - speed
    - youtube
    - openai
    - netflix
    - disney

save:
  # Save method: webdav, http, gist, or r2
  method: webdav
  # Save port
  port: 8080
  # WebDAV
  webdav-url: ""
  webdav-username: ""
  webdav-password: “"
  # GitHub token
  github-token: ""
  # Gist ID
  github-gist-id: ""
  # GitHub API mirror
  github-api-mirror: ""
  # Worker URL
  worker-url: 
  # Worker token
  worker-token: 

# mihomo api
mihomo-api-url: ""
# mihomo api secret
mihomo-api-secret: ""
# Retry count for subscription URLs
sub-urls-retry: 3
# Proxy settings, supports http and socks proxies

# Subscription URLs
sub-urls:
```

### 描述

~/mc $ cd ~/mc && go build -o mc main.go && ./mc -f /storage/emulated/0/1/config/config.yaml -r /storage/emulated/0/1/config/rename.yaml                                
INFO  [2025-03-08T05:45:23] bestsub version:            
INFO  [2025-03-08T05:45:23] concurrents: 100            
INFO  [2025-03-08T05:45:23] save method: webdav         
INFO  [2025-03-08T05:45:23] rename method: regex
INFO  [2025-03-08T05:45:23] not use proxy               
INFO  [2025-03-08T05:45:23] progress display: false     
INFO  [2025-03-08T05:45:23] check items: [speed youtube openai netflix disney]                                  
INFO  [2025-03-08T05:45:23] speed check concurrent: 1   
INFO  [2025-03-08T05:45:23] config file watcher started
INFO  [2025-03-08T05:45:23] currently, there are 32 subscription links set                                      
INFO  [2025-03-08T05:46:50] get proxies success: 2890 proxies                                                   
INFO  [2025-03-08T05:46:56] deduplicate proxies: 1680 proxies                                                   
INFO  [2025-03-08T05:47:43] check end 274 proxies       
INFO  [2025-03-08T05:47:43] start speed test
INFO  [2025-03-08T05:47:44] end speed test              
INFO  [2025-03-08T05:47:44] start rename proxies        
INFO  [2025-03-08T05:47:44] end rename proxies          
INFO  [2025-03-08T05:47:44] webdav upload success: all.yaml                                                     
INFO  [2025-03-08T05:47:44] webdav upload success: openai.yaml                                                  
INFO  [2025-03-08T05:47:45] webdav upload success: youtube.yaml                                                 
INFO  [2025-03-08T05:47:45] webdav upload success: netflix.yaml                                                 
INFO  [2025-03-08T05:47:45] webdav upload success: disney.yaml                                                  
WARN  [2025-03-08T05:47:45] MihomoApiUrl not configured, skipping update                                        
INFO  [2025-03-08T05:47:45] next check time: 2025-03-08 06:17:45

上面是运行时的控制台输出，测速直接跳过了，节点名称里也只有国家和编号，没有速度显示

### 重现方式

项目是在termux中运行
cd ~/mc && go build -o mc main.go && ./mc -f /storage/emulated/0/1/config/config.yaml -r /storage/emulated/0/1/config/rename.yaml

### 日志

```shell

```
