### ISSUE TITLE
[Bug] 检查项目保存结果有问题

### ISSUE THREAD

**Issue by maple-spirit** [bestruirui/BestSub#54]
### 验证步骤

- [x] 由于项目处于积极开发阶段，配置文件可能会频繁更改，更新版本后出现问题请先阅读最新文档
- [x] 我已经阅读了 [Doc](https://github.com/bestruirui/BestSub/blob/master/doc/) 文件夹下所有文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/BestSub/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
# 是否打印进度 
print-progress: false

log-level: debug

# 重命名方法 api 或 regex 或 mix
rename:
  method: regex
  flag: true

check:
  # 并发
  concurrent: 100
  # 检查间隔,单位分钟
  interval: 60
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 2048
  # 下载测试超时时间 单位秒
  download-timeout: 10
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: (倍率|x\d+(\.\d+)?|\d+(\.\d+)?x)
  # 测速并发
  speed-check-concurrent: 1
  # 测速数量
  speed-count: 10
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    - openai
    - youtube
    - netflix
    - disney
    - speed

save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method: gist
  # http保存方式下的端口
  port: 18989
  # GitHub token
  github-token: "XXXXX"
  # Gist ID
  github-gist-id: "XXXXX"

# mihomo api
mihomo-api-url: ""
# mihomo api secret
mihomo-api-secret: ""
# 重试次数
sub-urls-retry: 3
# 代理设置 支持 http 和 socks 代理
proxy:
  type: "" # 可选值: http, socks
  address: "http://192.168.31.11:7890" # 代理地址
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
  - XXXXX
  - XXXXX
```

### 描述

使用的是docker版，配置检查项目按默认的5个项目，采用gist上传保存，但保存结果为旧版本的 all.yaml 、youtube netflix  disney没有speed这一项，并且all.yaml中的数量少于其它几个。

### 重现方式

DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇵🇰 PK 156 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇵🇰 PK 157 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇵🇰 PK 158 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇹🇼 TW 159 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇭🇰 HK 160 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:38 proxy 🇺🇳 UN 161 speed 0 does not meet the condition, skipping
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:104 save all.yaml category 11 proxies
INFO  [2025-03-10T17:25:38] gist upload success: all.yaml
DEBUG [2025-03-10T17:25:38] thub.com/bestruirui/bestsub/proxy/saver/saver.go:104 save openai.yaml category 128 proxies
INFO  [2025-03-10T17:25:39] gist upload success: openai.yaml
DEBUG [2025-03-10T17:25:39] thub.com/bestruirui/bestsub/proxy/saver/saver.go:104 save youtube.yaml category 53 proxies
INFO  [2025-03-10T17:25:40] gist upload success: youtube.yaml
DEBUG [2025-03-10T17:25:40] thub.com/bestruirui/bestsub/proxy/saver/saver.go:104 save netflix.yaml category 18 proxies
INFO  [2025-03-10T17:25:41] gist upload success: netflix.yaml
DEBUG [2025-03-10T17:25:41] thub.com/bestruirui/bestsub/proxy/saver/saver.go:104 save disney.yaml category 38 proxies
INFO  [2025-03-10T17:25:41] gist upload success: disney.yaml
WARN  [2025-03-10T17:25:41] MihomoApiUrl not configured, skipping update
INFO  [2025-03-10T17:25:41] next check time: 2025-03-10 18:25:41

### 日志

```shell

```
