### ISSUE TITLE
[Bug]  Proxy Authentication Required

### ISSUE THREAD

**Issue by GuyCui** [bestruirui/BestSub#61]
### 验证步骤

- [x] 由于项目处于积极开发阶段，配置文件可能会频繁更改，更新版本后出现问题请先阅读最新文档
- [x] 我已经阅读了 [Doc](https://github.com/bestruirui/BestSub/blob/master/doc/) 文件夹下所有文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/BestSub/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
# 是否打印进度 
print-progress: false
log-level: debug
# 重命名方法 api 或 regex 或 mix
rename:
  method: regex
  flag: true
check:
  # 并发
  concurrent: 100
  # 检查间隔,单位分钟
  interval: 10
  # 超时时间 单位毫秒
  timeout: 2000
  # 最低测速 单位KB/s
  min-speed: 2048
  # 下载测试超时时间 单位秒
  download-timeout: 10
  # 测速下载大小 单位MB
  download-size: 50
  # 测速地址
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # 跳过测速的名称
  speed-skip-name: (倍率|x\d+(\.\d+)?|\d+(\.\d+)?x)
  # 测速并发
  speed-check-concurrent: 1
  # 测速数量
  speed-count: 10
  # 测速保存
  speed-save: true
  # 检查项目
  items:
    - openai
    - youtube
    - netflix
    - disney
    - speed
save:
  # 保存方法 webdav 或 http 或 gist 或 r2
  method:
    - http 
    - gist
  # 保存端口
  port: 8080
  github-token: ""
  github-gist-id: ""
  # github-api-mirror: "https://best-sub.xxx.dev/github"
# mihomo api
# mihomo-api-url: "http://192.168.x.x:9090"
# mihomo api secret
# mihomo-api-secret: "3"
# 重试次数
sub-urls-retry: 3
# 代理设置 支持 http 和 socks 代理
proxy:
  type: "http" # 可选值: http, socks
  address: "http://192.168.x.x:7890" # 代理地址
  password: ""
  username: ""
# 订阅链接
# type-include:
#   - ss
#   - vmess
sub-urls:
```

### 描述

使用上面的配置文件运行报错 Proxy Authentication Required

### 重现方式

docker 启动查看日志

### 日志

```shell
INFO  [2025-03-14T09:17:35] subscription links count: 4
WARN  [2025-03-14T09:17:37] subscription link: https://.cfd/client/...36 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
WARN  [2025-03-14T09:17:37] subscription link: https://.com/s/...5a get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
WARN  [2025-03-14T09:17:37] subscription link: https://.cn/client/...e5 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
WARN  [2025-03-14T09:17:37] subscription link: https://.top/s/...30 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
INFO  [2025-03-14T09:17:37] get proxies success: 0 proxies
INFO  [2025-03-14T09:17:37] deduplicate proxies: 0 proxies
INFO  [2025-03-14T09:17:37] check end 0 proxies
INFO  [2025-03-14T09:17:37] start speed test concurrent 1
INFO  [2025-03-14T09:17:37] end speed test
WARN  [2025-03-14T09:17:37] all.yaml proxies are empty, skip
WARN  [2025-03-14T09:17:37] openai.yaml proxies are empty, skip
WARN  [2025-03-14T09:17:37] youtube.yaml proxies are empty, skip
WARN  [2025-03-14T09:17:37] netflix.yaml proxies are empty, skip
WARN  [2025-03-14T09:17:37] disney.yaml proxies are empty, skip
WARN  [2025-03-14T09:17:37] MihomoApiUrl not configured, skipping update
INFO  [2025-03-14T09:17:37] next check time: 2025-03-14 09:27:37
```

**Comment by molezz** [comment]
192.168 地址？ 这个是不是mihomo没有启用 lan 共享功能 ？

**Comment by bestruirui** [comment]
> ### 验证步骤
> * [x]  由于项目处于积极开发阶段，配置文件可能会频繁更改，更新版本后出现问题请先阅读最新文档[x]  我已经阅读了 [Doc](https://github.com/bestruirui/BestSub/blob/master/doc/) 文件夹下所有文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。[x]  我已在 [Issue Tracker](https://github.com/bestruirui/BestSub/issues) 中寻找过我要提出的问题，并且没有找到
> 
> ### 配置文件
> # 是否打印进度 
> print-progress: false
> log-level: debug
> # 重命名方法 api 或 regex 或 mix
> rename:
>   method: regex
>   flag: true
> check:
>   # 并发
>   concurrent: 100
>   # 检查间隔,单位分钟
>   interval: 10
>   # 超时时间 单位毫秒
>   timeout: 2000
>   # 最低测速 单位KB/s
>   min-speed: 2048
>   # 下载测试超时时间 单位秒
>   download-timeout: 10
>   # 测速下载大小 单位MB
>   download-size: 50
>   # 测速地址
>   speed-test-url:
>     - https://speed.cloudflare.com/__down?bytes=1073741824
>     - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
>   # 跳过测速的名称
>   speed-skip-name: (倍率|x\d+(\.\d+)?|\d+(\.\d+)?x)
>   # 测速并发
>   speed-check-concurrent: 1
>   # 测速数量
>   speed-count: 10
>   # 测速保存
>   speed-save: true
>   # 检查项目
>   items:
>     - openai
>     - youtube
>     - netflix
>     - disney
>     - speed
> save:
>   # 保存方法 webdav 或 http 或 gist 或 r2
>   method:
>     - http 
>     - gist
>   # 保存端口
>   port: 8080
>   github-token: ""
>   github-gist-id: ""
>   # github-api-mirror: "https://best-sub.xxx.dev/github"
> # mihomo api
> # mihomo-api-url: "http://192.168.x.x:9090"
> # mihomo api secret
> # mihomo-api-secret: "3"
> # 重试次数
> sub-urls-retry: 3
> # 代理设置 支持 http 和 socks 代理
> proxy:
>   type: "http" # 可选值: http, socks
>   address: "http://192.168.x.x:7890" # 代理地址
>   password: ""
>   username: ""
> # 订阅链接
> # type-include:
> #   - ss
> #   - vmess
> sub-urls:
> ### 描述
> 使用上面的配置文件运行报错 Proxy Authentication Required
> 
> ### 重现方式
> docker 启动查看日志
> 
> ### 日志
> INFO  [2025-03-14T09:17:35] subscription links count: 4
> WARN  [2025-03-14T09:17:37] subscription link: https://.cfd/client/...36 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> WARN  [2025-03-14T09:17:37] subscription link: https://.com/s/...5a get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> WARN  [2025-03-14T09:17:37] subscription link: https://.cn/client/...e5 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> WARN  [2025-03-14T09:17:37] subscription link: https://.top/s/...30 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> INFO  [2025-03-14T09:17:37] get proxies success: 0 proxies
> INFO  [2025-03-14T09:17:37] deduplicate proxies: 0 proxies
> INFO  [2025-03-14T09:17:37] check end 0 proxies
> INFO  [2025-03-14T09:17:37] start speed test concurrent 1
> INFO  [2025-03-14T09:17:37] end speed test
> WARN  [2025-03-14T09:17:37] all.yaml proxies are empty, skip
> WARN  [2025-03-14T09:17:37] openai.yaml proxies are empty, skip
> WARN  [2025-03-14T09:17:37] youtube.yaml proxies are empty, skip
> WARN  [2025-03-14T09:17:37] netflix.yaml proxies are empty, skip
> WARN  [2025-03-14T09:17:37] disney.yaml proxies are empty, skip
> WARN  [2025-03-14T09:17:37] MihomoApiUrl not configured, skipping update
> INFO  [2025-03-14T09:17:37] next check time: 2025-03-14 09:27:37

看一下你的配置文件是不是设置认证了 https://wiki.metacubex.one/config/general/#_2

**Comment by GuyCui** [comment]
> > ### 验证步骤
> > 
> > 
> > * [x]   由于项目处于积极开发阶段，配置文件可能会频繁更改，更新版本后出现问题请先阅读最新文档[x]  我已经阅读了 [Doc](https://github.com/bestruirui/BestSub/blob/master/doc/) 文件夹下所有文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。[x]  我已在 [Issue Tracker](https://github.com/bestruirui/BestSub/issues) 中寻找过我要提出的问题，并且没有找到
> > ### 配置文件
> > # 是否打印进度
> > print-progress: false
> > log-level: debug打印进度：false
> > log-level： debug （日志级别：调试）
> > # 重命名方法 api 或 regex 或 mix
> > rename:
> > method: regex
> > flag: true
> > check:重命名：
> > 方法：Regex
> > 标志： true
> > 检查：
> > # 并发
> > concurrent: 100 并发： 100
> > # 检查间隔,单位分钟
> > interval: 10 间隔： 10
> > # 超时时间 单位毫秒
> > timeout: 2000 超时：2000
> > # 最低测速 单位KB/s
> > min-speed: 2048 最小速度：2048
> > # 下载测试超时时间 单位秒
> > download-timeout: 10下载超时：10
> > # 测速下载大小 单位MB
> > download-size: 50 下载大小： 50
> > # 测速地址
> > speed-test-url:
> > - https://speed.cloudflare.com/__down?bytes=1073741824
> > - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpmspeed-test-url 的 URL：
> > - https://speed.cloudflare.com/__down?bytes=1073741824
> > - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
> > # 跳过测速的名称
> > speed-skip-name: (倍率|x\d+(.\d+)?|\d+(.\d+)?x)speed-skip-name： （倍率|x\d+（.\d+）？|\d+（.\d+）？x）
> > # 测速并发
> > speed-check-concurrent: 1speed-check-concurrent：1
> > # 测速数量
> > speed-count: 10 速度计数： 10
> > # 测速保存
> > speed-save: true speed-save：真
> > # 检查项目
> > items:
> > - openai
> > - youtube
> > - netflix
> > - disney
> > - speed
> > save:项目：
> > - OpenAI 公司
> > - 优酷
> > - 网飞
> > -迪斯尼
> > -速度
> > 救：
> > # 保存方法 webdav 或 http 或 gist 或 r2
> > method:
> > - http
> > - gist方法：
> > - HTTP 协议
> > -要点
> > # 保存端口
> > port: 8080
> > github-token: ""
> > github-gist-id: ""端口：8080
> > github-token： “”
> > github-gist-id： “”
> > # github-api-mirror: "https://best-sub.xxx.dev/github"github-api-mirror： “https://best-sub.xxx.dev/github”
> > # mihomo api Mihomo API
> > # mihomo-api-url: "http://192.168.x.x:9090"mihomo-api-url： “http://192.168.x.x:9090”
> > # mihomo api secret Mihomo API 秘密
> > # mihomo-api-secret: "3"mihomo-api-secret： “3”
> > # 重试次数
> > sub-urls-retry: 3 子 urls-retry：3
> > # 代理设置 支持 http 和 socks 代理
> > proxy:
> > type: "http" # 可选值: http, socks
> > address: "http://192.168.x.x:7890" # 代理地址
> > password: ""
> > username: ""代理：
> > type： “http” # 可选值： http， socks
> > address： “http://192.168.x.x:7890” # 代理地址
> > 密码： “”
> > 用户名： “”
> > # 订阅链接
> > # type-include: type-include 的
> > # - ss
> > # - vmess
> > sub-urls: 子 URL：
> > ### 描述
> > 使用上面的配置文件运行报错 Proxy Authentication Required
> > ### 重现方式
> > docker 启动查看日志
> > ### 日志
> > INFO  [2025-03-14T09:17:35] subscription links count: 4
> > WARN  [2025-03-14T09:17:37] subscription link: https://.cfd/client/...36 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> > WARN  [2025-03-14T09:17:37] subscription link: https://.com/s/...5a get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> > WARN  [2025-03-14T09:17:37] subscription link: https://.cn/client/...e5 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> > WARN  [2025-03-14T09:17:37] subscription link: https://.top/s/...30 get data failed: failed after 3 retries: Get "https://": Proxy Authentication Required
> > INFO  [2025-03-14T09:17:37] get proxies success: 0 proxies
> > INFO  [2025-03-14T09:17:37] deduplicate proxies: 0 proxies
> > INFO  [2025-03-14T09:17:37] check end 0 proxies
> > INFO  [2025-03-14T09:17:37] start speed test concurrent 1
> > INFO  [2025-03-14T09:17:37] end speed test
> > WARN  [2025-03-14T09:17:37] all.yaml proxies are empty, skip
> > WARN  [2025-03-14T09:17:37] openai.yaml proxies are empty, skip
> > WARN  [2025-03-14T09:17:37] youtube.yaml proxies are empty, skip
> > WARN  [2025-03-14T09:17:37] netflix.yaml proxies are empty, skip
> > WARN  [2025-03-14T09:17:37] disney.yaml proxies are empty, skip
> > WARN  [2025-03-14T09:17:37] MihomoApiUrl not configured, skipping update
> > INFO  [2025-03-14T09:17:37] next check time: 2025-03-14 09:27:37信息 [2025-03-14T09：17：35] 订阅链接数： 4
> > 警告 [2025-03-14T09：17：37] 订阅链接：https：//.cfd/client/...36 获取数据失败：重试 3 次失败：获取“https://”：需要代理身份验证
> > 警告 [2025-03-14T09：17：37] 订阅链接：https：//.com/s/...5a 获取数据失败：重试 3 次失败：获取 “https://”：需要代理身份验证
> > 警告 [2025-03-14T09：17：37] 订阅链接： https：//.cn/client/...e5 获取数据失败：重试 3 次后失败：获取“https://”：需要代理身份验证
> > 警告 [2025-03-14T09：17：37] 订阅链接：https：//.top/s/...30 次获取数据失败：重试 3 次失败：获取“https://”：需要代理身份验证
> > 信息 [2025-03-14T09：17：37] 获取代理成功：0 个代理
> > 信息 [2025-03-14T09：17：37] 重复数据删除代理：0 个代理
> > 信息 [2025-03-14T09：17：37] 检查结束 0 个代理
> > 信息 [2025-03-14T09：17：37] 启动速度测试并发 1
> > 信息 [2025-03-14T09：17：37] 结束速度测试
> > 警告 [2025-03-14T09：17：37] all.yaml 代理为空，跳过
> > 警告 [2025-03-14T09：17：37] openai.yaml 代理为空，跳过
> > 警告 [2025-03-14T09：17：37] youtube.yaml 代理为空，跳过
> > 警告 [2025-03-14T09：17：37] netflix.yaml 代理为空，跳过
> > 警告 [2025-03-14T09：17：37] disney.yaml 代理为空，跳过
> > 警告 [2025-03-14T09：17：37] 未配置 MihomoApiUrl，跳过更新
> > 信息 [2025-03-14T09：17：37] 下次查看时间：2025-03-14 09：27：37
> 
> 看一下你的配置文件是不是设置认证了 https://wiki.metacubex.one/config/general/#_2
是的 设置认证了 但是下面的 我填入了 之前提过 你不是新增加了这两个配置吗
address: "http://192.168.x.x:7890/" # 代理地址
password: "密码"
username: "用户名"

**Comment by bestruirui** [comment]
你用的版本号是多少？是最新版吗？我无法复现

**Comment by GuyCui** [comment]
> 你用的版本号是多少？是最新版吗？我无法复现

是的 最新的 docker compose 增加password: "密码"和username: "用户名"这个两个是昨天更新了吗 还是没有进行更新？

**Comment by bestruirui** [comment]
> > 你用的版本号是多少？是最新版吗？我无法复现
> 
> 是的 最新的 docker compose 增加password: "密码"和username: "用户名"这个两个是昨天更新了吗 还是没有进行更新？

我看一下你的日志，日志有打印版本号

**Comment by GuyCui** [comment]
> > > 你用的版本号是多少？是最新版吗？我无法复现
> > 
> > 
> > 是的 最新的 docker compose 增加password: "密码"和username: "用户名"这个两个是昨天更新了吗 还是没有进行更新？
> 
> 我看一下你的日志，日志有打印版本号

INFO  [2025-03-14T11:14:31] bestsub version: 0.3.0
INFO  [2025-03-14T11:14:31] concurrents: 100
INFO  [2025-03-14T11:14:31] save methods: [http gist]
INFO  [2025-03-14T11:14:31] rename method: regex
INFO  [2025-03-14T11:14:31] proxy type: http
INFO  [2025-03-14T11:14:31] progress display: false
是这个吗

**Comment by GuyCui** [comment]
> > > 你用的版本号是多少？是最新版吗？我无法复现
> > 
> > 
> > 是的 最新的 docker compose 增加password: "密码"和username: "用户名"这个两个是昨天更新了吗 还是没有进行更新？
> 
> 我看一下你的日志，日志有打印版本号

WARN  [2025-03-14T11:14:58] all.yaml proxies are empty, skip
WARN  [2025-03-14T11:14:58] openai.yaml proxies are empty, skip
WARN  [2025-03-14T11:14:58] youtube.yaml proxies are empty, skip
WARN  [2025-03-14T11:14:58] netflix.yaml proxies are empty, skip
WARN  [2025-03-14T11:14:58] disney.yaml proxies are empty, skip
WARN  [2025-03-14T11:14:58] MihomoApiUrl not configured, skipping update
还有就是提示这个 all 都为空 是什么意思 
 # 检查项目
  items:
    - openai
    - youtube
    - netflix
    - disney
    - speed
    这里我都填入了

**Comment by bestruirui** [comment]
```
proxy:
  type: "http" # 可选值: http, socks
  address: "http://127.0.0.1:7890" # 代理地址
  username: "user1"
  password: "pass1"
```
```
port: 7890
socks-port: 7891
mixed-port: 10801
redir-port: 7892
tproxy-port: 7893
allow-lan: true
authentication:
  - "user1:pass1"
# skip-auth-prefixes:
#   - 127.0.0.1/32
secret: ""
unified-delay: false
tcp-concurrent: true
geodata-mode: false
lan-allowed-ips:
    - 0.0.0.0/0
    - ::/0
lan-disallowed-ips: []

```


没有问题，你自己改一下你自己的配置文件
