### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FlechazoPh** [bestruirui/BestSub#65]
### 验证步骤

- [x] 由于项目处于积极开发阶段，配置文件可能会频繁更改，更新版本后出现问题请先阅读最新文档
- [x] 我已经阅读了 [Doc](https://github.com/bestruirui/BestSub/blob/master/doc/) 文件夹下所有文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [x] 我已在 [Issue Tracker](https://github.com/bestruirui/BestSub/issues) 中寻找过我要提出的问题，并且没有找到

### 配置文件

```yaml
# Whether to print progress
print-progress: true

rename:
  # Renaming method: api, regex, or mix
  method: mix
  # Whether to show flag information
  flag: true

check:
  # Concurrency
  concurrent: 100
  # Check interval, in minutes
  interval: 60
  # Timeout, in milliseconds
  timeout: 2000
  # Minimum speed, in KB/s
  min-speed: 2048
  # Download test timeout, in seconds
  download-timeout: 30
  # Speed test download size, in MB
  download-size: 50
  # Speed test URL
  speed-test-url:
    - https://speed.cloudflare.com/__down?bytes=1073741824
    - https://github.com/VSCodium/vscodium/releases/download/1.98.0.25067/codium-1.98.0.25067-el9.aarch64.rpm
  # Skip speed test for names matching this regex
#   speed-skip-name: (倍率|x\d+(\.\d+)?|\d+(\.\d+)?x)
  # Speed test concurrent
  speed-check-concurrent: 1
  # Speed test count
  speed-count: 5000
  # Speed save
  speed-save: true
  # Items to check
  items:
    - speed
    - youtube
    - openai
    - netflix
    - disney

save:
  # Save method: webdav, http, gist, or r2
  method: 
    - local
    - gist
  before-save-do:
    # - /app/config/notify_start.sh
  after-save-do:
    - /app/config/tg-notice.sh
  # Save port
#   port: 8080
  # WebDAV
#   webdav-url: "https://webdav.company/dav"
#   webdav-username: "username"
#   webdav-password: "password"
  # GitHub token
  github-token: "xxxxx"
  # Gist ID
  github-gist-id: "xxxxxx"
  # GitHub API mirror
#   github-api-mirror: "http://githubproxy.extingstudio.workers.dev/github"
  # Worker URL
#   worker-url: https://your-worker-url.com
  # Worker token
#   worker-token: your-worker-token

# mihomo api
# mihomo-api-url: "http://192.168.31.11:9090"
# mihomo api secret
# mihomo-api-secret: ""
# Retry count for subscription URLs
sub-urls-retry: 3
# Proxy settings, supports http and socks proxies
# proxy:
#   type: "http" # Options: http, socks
#   address: "http://192.168.31.11:7890" # Proxy address
# Subscription URLs
# type-include:
#   - ss
#   - vmess
sub-urls:
  - https://gist.githubusercontent.com.yaml
  - https://gist.githubusercontent.com/.yaml
  - https://.yaml
  - https://gist.githubusercontent.com.yaml
  - https://gist.githubusercontent.com.yaml
  - https://raw.githubusercontent.com/.yaml
  - https://raw.githubusercontent.com
  - https://raw.githubusercontent.com.yaml
  - https://raw.githubusercontent.com/.yml
  - https://.yaml
```

### 描述

服务器是 首尔甲骨文，系统:CentOS 7.9.2009 x86_64(Py3.7.9)　 
配置： 1核 1G

订阅大概10个，脚本跑出来的节点大概2000多个，日志里看 check end 53 proxies，这条每次大概出来4,50条，配置速度在2MB/S以上，最后大概能拿到2,30条节点，不知道是不是服务器问题，节点比较少。

配置了 print-progress: true，但是日志不显示进度。

另外日志有什么办法持久化到本地日志文件么,  > Test.log

### 重现方式

无

### 日志

```shell
下面是日志：

`
bestsub       | INFO  [2025-03-25T15:16:06] subscription links count: 10
bestsub       | INFO  [2025-03-25T15:16:09] get proxies success: 2771 proxies
bestsub       | INFO  [2025-03-25T15:16:16] deduplicate proxies: 255 proxies
bestsub       | INFO  [2025-03-25T15:17:02] check end 53 proxies
bestsub       | INFO  [2025-03-25T15:17:02] start speed test concurrent 1
bestsub       | INFO  [2025-03-25T15:32:45] end speed test
bestsub       | INFO  [2025-03-25T15:32:48] gist upload success: all.yaml
bestsub       | INFO  [2025-03-25T15:32:50] gist upload success: speed.yaml
bestsub       | WARN  [2025-03-25T15:32:50] openai.yaml proxies are empty, skip
bestsub       | INFO  [2025-03-25T15:32:59] gist upload success: youtube.yaml
bestsub       | INFO  [2025-03-25T15:33:07] gist upload success: netflix.yaml
bestsub       | INFO  [2025-03-25T15:33:15] gist upload success: disney.yaml
bestsub       | INFO  [2025-03-25T15:33:15] Executing after-save scripts
bestsub       | INFO  [2025-03-25T15:33:15] Executing script: /app/config/tg-notice.sh
bestsub       | INFO  [2025-03-25T15:33:15] Logging output to: /app/config/tg-notice.sh.log
bestsub       | WARN  [2025-03-25T15:33:17] MihomoApiUrl not configured, skipping update

`

`

bestsub       | INFO  [2025-03-25T16:33:17] subscription links count: 10
bestsub       | INFO  [2025-03-25T16:33:19] get proxies success: 2819 proxies
bestsub       | INFO  [2025-03-25T16:33:27] deduplicate proxies: 263 proxies
bestsub       | INFO  [2025-03-25T16:35:09] check end 60 proxies
bestsub       | INFO  [2025-03-25T16:35:09] start speed test concurrent 1
bestsub       | INFO  [2025-03-25T16:55:15] end speed test
bestsub       | INFO  [2025-03-25T16:55:17] gist upload success: all.yaml
bestsub       | INFO  [2025-03-25T16:55:18] gist upload success: speed.yaml
bestsub       | WARN  [2025-03-25T16:55:18] openai.yaml proxies are empty, skip
bestsub       | INFO  [2025-03-25T16:55:19] gist upload success: youtube.yaml
bestsub       | INFO  [2025-03-25T16:55:19] gist upload success: netflix.yaml
bestsub       | INFO  [2025-03-25T16:55:20] gist upload success: disney.yaml
bestsub       | INFO  [2025-03-25T16:55:20] Executing after-save scripts
bestsub       | INFO  [2025-03-25T16:55:20] Executing script: /app/config/tg-notice.sh
bestsub       | INFO  [2025-03-25T16:55:20] Logging output to: /app/config/tg-notice.sh.log
bestsub       | WARN  [2025-03-25T16:55:25] MihomoApiUrl not configured, skipping update
bestsub       | INFO  [2025-03-25T16:55:25] next check time: 2025-03-25 17:55:25

`
```
